
services:
  ros2_ws:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ros2_ws:humble
    container_name: ros2_ws
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/ros2_ws
      - ./secrets:/root/spot_configs:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  zenoh_router:
    image: eclipse/zenoh:latest
    container_name: zenoh_router
    network_mode: host
    volumes:
      - ./zenoh-config.json5:/config.json5
    command:
      -c /config.json5
    restart: unless-stopped
